### ISSUE TITLE
Поиск хостинга для сервера и базы данных.

### ISSUE THREAD

**Issue by romikabi** [TramIncorporated/tram-server#2]
Для начала предлагаю поискать бесплатные/дешевые места для размещения. База обещает быть большая, поэтому надо задуматься о альтернативных платных ресурсах.
Нужно глянуть Google Big Query.

**Comment by nicklyu** [comment]
Предлагаю для начала попробовать бесплатные хостинги. Раз имеется концепт базы, то можно посмотреть [elephantsql](https://www.elephantsql.com/plans.html) и [heroku](https://www.heroku.com/pricing#databases)

**Comment by nicklyu** [comment]
Для сервера выбран heroku. Если варианты для базы изменятся, то отроем еще раз

**Comment by nicklyu** [comment]
Для базы пусть будет elephantsql, проще взаимодействовать.
