### ISSUE TITLE
Найти подходящий источник данных о фильмах. 

### ISSUE THREAD

**Issue by romikabi** [TramIncorporated/tram-server#3]
Глянуть TMDb, OMDb и другие.

**Comment by nicklyu** [comment]
[Еще один вариант](http://www.omdbapi.com/)
По сути за доллар 100000 запросов ежедневно, а за 5 еще и постер api ([условия](https://www.patreon.com/bePatron?u=5038490))

**Comment by romikabi** [comment]
[TMDb](https://www.themoviedb.org/documentation/api)
[Информация о лицензии](https://www.themoviedb.org/documentation/api/terms-of-use)

Ну и плюс [дока](https://developers.themoviedb.org/3/collections) к этому апи

**Comment by romikabi** [comment]
(imdb)[http://www.imdb.com/interfaces/]

**Comment by nicklyu** [comment]
Останавливаемся на TMDb 
Удобный api, нет ограничений на доступ к информации и файлам
